export const INITIAL_REQUEST_ANGEL_START = "INITIAL_REQUEST_ANGEL_START";
export const INITIAL_REQUEST_ANGEL_SUCCESS = "INITIAL_REQUEST_ANGEL_SUCCESS";

export const REQUEST_ANGEL_START = "REQUEST_ANGEL_START";
export const REQUEST_ANGEL_SUCCESS = "REQUEST_ANGEL_SUCCESS";

export const REGISTER_ANGEL_START = "REGISTER_ANGEL_START";
export const REGISTER_ANGEL_SUCCESS = "REGISTER_ANGEL_SUCCESS";

export const UPDATE_ANGEL_START = "UPDATE_ANGEL_START";
export const UPDATE_ANGEL_SUCCESS = "UPDATE_ANGEL_SUCCESS";

export const DELETE_ANGEL_START = "DELETE_ANGEL_START";
export const DELETE_ANGEL_SUCCESS = "DELETE_ANGEL_SUCCESS";